import type { ScanReport, ParsedDocument, SiteInfo, GenerateOutput } from './types.js';

const AI_CRAWLERS = [
  { name: 'GPTBot', description: 'OpenAI model-training crawler control' },
  { name: 'ChatGPT-User', description: 'OpenAI user-initiated browsing control' },
  { name: 'ClaudeBot', description: 'Anthropic crawler control' },
  { name: 'PerplexityBot', description: 'Perplexity search crawler control' },
  { name: 'Google-Extended', description: 'Google model-training usage control; not Google Search indexing' },
  { name: 'Applebot-Extended', description: 'Apple generative-model usage control' },
  { name: 'CCBot', description: 'Common Crawl control' },
];

export function generateLlmsTxt(report: ScanReport, siteInfo: SiteInfo): string {
  const lines: string[] = [];

  lines.push(`# ${siteInfo.name}`);
  lines.push('');
  lines.push(`> ${siteInfo.description}`);
  lines.push('');

  if (report.pages.length > 0) {
    lines.push('## Pages');
    lines.push('');
    for (const page of report.pages) {
      const url = page.url;
      lines.push(`- [${page.title}](${url}): content-readiness score ${page.scores.total}/100`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function generateLlmsFullTxt(report: ScanReport, pages: ParsedDocument[]): string {
  const lines: string[] = [];

  for (const page of pages) {
    lines.push(`## ${page.title}`);
    lines.push('');
    const maxChars = 5000;
    lines.push(page.rawText.slice(0, maxChars));
    if (page.rawText.length > maxChars) {
      lines.push(`\n[Content truncated: ${page.rawText.length} chars total, showing first ${maxChars}]`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

export function generateJsonLd(doc: ParsedDocument): object[] {
  const existing = new Set(doc.jsonLd.map((ld) => ld['@type']).filter(Boolean));
  const generated: object[] = [];

  // Add an Article candidate only when visible structure and explicit metadata agree.
  if (!existing.has('Article') && !existing.has('TechArticle') && !existing.has('BlogPosting')) {
    const hasArticleContainer = /<article\b/i.test(doc.html || '');
    const author = doc.metaTags['author'];
    const datePublished = doc.metaTags['article:published_time'] || doc.metaTags['date'];
    if (hasArticleContainer && author && datePublished && doc.headings.length >= 2 && doc.paragraphs.length >= 3) {
      generated.push({
        '@context': 'https://schema.org',
        '@type': 'Article',
        name: doc.title,
        description: doc.metaTags['description'] || doc.paragraphs[0]?.slice(0, 160) || '',
        author: { '@type': 'Person', name: author },
        datePublished,
      });
    }
  }

  // FAQPage is intentionally not inferred from headings. Generated structured data
  // must match visible content and the eligibility rules of the target search feature.

  // Add BreadcrumbList from nav links if not present
  if (!existing.has('BreadcrumbList')) {
    const navLinks = doc.links.filter((l) => l.href.startsWith('/') && l.text.length > 0).slice(0, 5);
    if (navLinks.length >= 2) {
      generated.push({
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: navLinks.map((link, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          name: link.text,
          item: link.href,
        })),
      });
    }
  }

  return generated;
}

export function generateRobotsTxtSuggestions(existingRobots: string | null): string[] {
  const suggestions: string[] = [];
  const existing = existingRobots || '';

  suggestions.push('# AI Crawler Configuration');
  suggestions.push('# Generated by geo-cli');
  suggestions.push('');

  for (const crawler of AI_CRAWLERS) {
    const isConfigured = new RegExp(`User-agent:\\s*${crawler.name}`, 'i').test(existing);
    if (!isConfigured) {
      suggestions.push(`# ${crawler.description}`);
      suggestions.push(`User-agent: ${crawler.name}`);
      suggestions.push('Allow: /');
      suggestions.push('');
    }
  }

  return suggestions;
}

export function generate(report: ScanReport, pages: ParsedDocument[], siteInfo: SiteInfo, existingRobots?: string | null): GenerateOutput {
  return {
    llmsTxt: generateLlmsTxt(report, siteInfo),
    llmsFullTxt: generateLlmsFullTxt(report, pages),
    jsonLd: pages.flatMap((p) => generateJsonLd(p)),
    robotsTxtSuggestions: generateRobotsTxtSuggestions(existingRobots ?? null),
  };
}
